### ISSUE TITLE
PhotosFlow can't be installed by following the documentation

### ISSUE THREAD

**Issue by afiskon** [pothosware/homebrew-pothos#37] opened 2020-04-14 11:44 UTC
I tried to follow https://github.com/pothosware/homebrew-pothos/wiki

However the step "Install software" fails:

```
$ brew install pothosflow
Updating Homebrew...
==> Installing pothosflow from pothosware/pothos
==> Installing dependencies for pothosware/pothos/pothosflow: pothos, qt5, freetype, webp, gd, python@3.8, glib, jasper, netpbm, gts and graphviz
==> Installing pothosware/pothos/pothosflow dependency: pothos
==> Downloading https://github.com/pothosware/PothosCore/archive/pothos-0.6.1.tar.gz
Already downloaded: /Users/eax/Library/Caches/Homebrew/downloads/3643acb550dd1b14ce913a36d15b92e81be83172959efb65683777b1a65f4a00--PothosCore-pothos-0.6.1.tar.gz
==> cmake .. -DPOTHOS_EXTVER=release -DPOTHOS_ROOT='/usr/local' -DENABLE_INTERNAL_POCO=OFF -DENABLE_INTERNAL_SPUCE=OFF -DENABLE_INTERNAL_
==> make install
Last 15 lines from /Users/eax/Library/Logs/Homebrew/pothos/02.make:
                   ^
/usr/local/include/Poco/Hash.h:96:20: note: candidate function
inline std::size_t hash(UInt64 n)
                   ^
[ 12%] Building CXX object lib/CMakeFiles/Pothos.dir/Object/Builtin/Compare.cpp.o
cd /tmp/pothos-20200414-9041-1e2moj2/PothosCore-pothos-0.6.1/build/lib && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++  -DPOCO_ENABLE_CPP11 -DPOCO_ENABLE_CPP14 -DPOCO_HAVE_IPv6 -DPOCO_NO_STAT64 -DPOCO_OS_FAMILY_UNIX -DPOTHOS_DLL_EXPORTS -DPOTHOS_LIBRARY_NAME=\"libPothos.0.6.1.dylib\" -DXML_DTD -I/tmp/pothos-20200414-9041-1e2moj2/PothosCore-pothos-0.6.1/include -I/tmp/pothos-20200414-9041-1e2moj2/PothosCore-pothos-0.6.1/lib -I/usr/local/include/muparserx -I/usr/local/include/nlohmann  -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -fPIC   -std=gnu++14 -o CMakeFiles/Pothos.dir/Object/Builtin/Compare.cpp.o -c /tmp/pothos-20200414-9041-1e2moj2/PothosCore-pothos-0.6.1/lib/Object/Builtin/Compare.cpp
[ 13%] Building CXX object lib/CMakeFiles/Pothos.dir/Object/Builtin/ConvertIntermediate.cpp.o
cd /tmp/pothos-20200414-9041-1e2moj2/PothosCore-pothos-0.6.1/build/lib && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++  -DPOCO_ENABLE_CPP11 -DPOCO_ENABLE_CPP14 -DPOCO_HAVE_IPv6 -DPOCO_NO_STAT64 -DPOCO_OS_FAMILY_UNIX -DPOTHOS_DLL_EXPORTS -DPOTHOS_LIBRARY_NAME=\"libPothos.0.6.1.dylib\" -DXML_DTD -I/tmp/pothos-20200414-9041-1e2moj2/PothosCore-pothos-0.6.1/include -I/tmp/pothos-20200414-9041-1e2moj2/PothosCore-pothos-0.6.1/lib -I/usr/local/include/muparserx -I/usr/local/include/nlohmann  -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -fPIC   -std=gnu++14 -o CMakeFiles/Pothos.dir/Object/Builtin/ConvertIntermediate.cpp.o -c /tmp/pothos-20200414-9041-1e2moj2/PothosCore-pothos-0.6.1/lib/Object/Builtin/ConvertIntermediate.cpp
1 error generated.
make[2]: *** [lib/CMakeFiles/Pothos.dir/Object/Compare.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1 error generated.
make[2]: *** [lib/CMakeFiles/Pothos.dir/Object/Convert.cpp.o] Error 1
make[1]: *** [lib/CMakeFiles/Pothos.dir/all] Error 2
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/pothosware/homebrew-pothos/issues
```

I'm using MacOS Catalina 10.15.3 and Homebrew 2.2.13

**Comment by guruofquality** [comment] 2020-04-14 14:22
it should be fixed upstream, build pothos with --head

**Comment by drfruct** [comment] 2020-05-02 21:15
After building the `pothos`, another error occurs:

```
CMake Error in CMakeLists.txt:
  Cannot use features from non-enabled language C
```

```
brew install pothosflow --verbose
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

==> Installing pothosflow from pothosware/pothos
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200503-9718-uz6s25.sb nice ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/pothosware/homebrew-pothos/pothosflow.rb --verbose
==> Downloading https://github.com/pothosware/PothosFlow/archive/pothos-flow-0.6.2.tar.gz
Already downloaded: /Users/some.user/Library/Caches/Homebrew/downloads/b008e8bd74f023a5e2e446d5ee245996f666d7a67187509081e5b998c7e1de58--PothosFlow-pothos-flow-0.6.2.tar.gz
==> Verifying b008e8bd74f023a5e2e446d5ee245996f666d7a67187509081e5b998c7e1de58--PothosFlow-pothos-flow-0.6.2.tar.gz checksum
tar xof /Users/some.user/Library/Caches/Homebrew/downloads/b008e8bd74f023a5e2e446d5ee245996f666d7a67187509081e5b998c7e1de58--PothosFlow-pothos-flow-0.6.2.tar.gz -C /private/tmp/d20200503-9719-j0s0ak
cp -pR /private/tmp/d20200503-9719-j0s0ak/PothosFlow-pothos-flow-0.6.2/. /private/tmp/pothosflow-20200503-9719-1hy2brx/PothosFlow-pothos-flow-0.6.2
chmod -Rf +w /private/tmp/d20200503-9719-j0s0ak
==> cmake .. -DBUNDLE_DESTINATION=. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/pothosflow/0.6.2 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk
-- The CXX compiler identification is AppleClang 11.0.3.11030032
-- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++
-- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Poco_VERSION: 1.10.1
-- Poco_INCLUDE_DIRS:
-- Poco_LIBRARIES: Poco::Foundation;Poco::Util;Poco::XML;Poco::Net
-- Module CoreEditWidgets configured with version: 0.6.2
-- Configuring done
CMake Error in CMakeLists.txt:
  Cannot use features from non-enabled language C


CMake Generate step failed.  Build files cannot be regenerated correctly.

==> Formula
Tap: pothosware/pothos
Path: /usr/local/Homebrew/Library/Taps/pothosware/homebrew-pothos/pothosflow.rb
==> Configuration
HOMEBREW_VERSION: 2.2.14
ORIGIN: https://github.com/Homebrew/brew
HEAD: e2bc0fa6879ce4c74ea2d8f8c654c9812f776b43
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4acfb7dfc2ad5927dbf3e4a07671aadc132797f7
Core tap last commit: 3 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.u9GcwmPN8d/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 11.0 build 1103
Git: 2.20.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.4-x86_64
CLT: 1103.0.32.59
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local/opt/openssl@1.1:/usr/local/opt/qt:/usr/local/opt/libffi:/usr/local/opt/readline:/usr/local/opt/sqlite:/usr/local/opt/python@3.8:/usr/local/opt/icu4c:/usr/local
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /usr/local/opt/qt/Frameworks:/usr/local/opt/python@3.8/Frameworks
PKG_CONFIG_PATH: /usr/local/opt/openssl@1.1/lib/pkgconfig:/usr/local/opt/muparserx/lib/pkgconfig:/usr/local/opt/pothos/lib/pkgconfig:/usr/local/opt/qt/lib/pkgconfig:/usr/local/opt/libpng/lib/pkgconfig:/usr/local/opt/freetype/lib/pkgconfig:/usr/local/opt/fontconfig/lib/pkgconfig:/usr/local/opt/jpeg/lib/pkgconfig:/usr/local/opt/libtiff/lib/pkgconfig:/usr/local/opt/webp/lib/pkgconfig:/usr/local/opt/gd/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig:/usr/local/opt/pcre/lib/pkgconfig:/usr/local/opt/readline/lib/pkgconfig:/usr/local/opt/sqlite/lib/pkgconfig:/usr/local/opt/xz/lib/pkgconfig:/usr/local/opt/python@3.8/lib/pkgconfig:/usr/local/opt/glib/lib/pkgconfig:/usr/local/opt/jasper/lib/pkgconfig:/usr/local/opt/netpbm/lib/pkgconfig:/usr/local/opt/gts/lib/pkgconfig:/usr/local/opt/lzo/lib/pkgconfig:/usr/local/opt/pixman/lib/pkgconfig:/usr/local/opt/cairo/lib/pkgconfig:/usr/local/opt/fribidi/lib/pkgconfig:/usr/local/opt/graphite2/lib/pkgconfig:/usr/local/opt/icu4c/lib/pkgconfig:/usr/local/opt/harfbuzz/lib/pkgconfig:/usr/local/opt/pango/lib/pkgconfig:/usr/local/opt/graphviz/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.15
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/local/opt/cmake/bin:/usr/local/opt/openssl@1.1/bin:/usr/local/opt/poco/bin:/usr/local/opt/pothos/bin:/usr/local/opt/qt/bin:/usr/local/opt/libpng/bin:/usr/local/opt/freetype/bin:/usr/local/opt/fontconfig/bin:/usr/local/opt/jpeg/bin:/usr/local/opt/libtiff/bin:/usr/local/opt/webp/bin:/usr/local/opt/gd/bin:/usr/local/opt/gettext/bin:/usr/local/opt/pcre/bin:/usr/local/opt/gdbm/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/xz/bin:/usr/local/opt/python@3.8/bin:/usr/local/opt/glib/bin:/usr/local/opt/jasper/bin:/usr/local/opt/netpbm/bin:/usr/local/opt/gts/bin:/usr/local/opt/libtool/bin:/usr/local/opt/cairo/bin:/usr/local/opt/fribidi/bin:/usr/local/opt/graphite2/bin:/usr/local/opt/icu4c/bin:/usr/local/opt/harfbuzz/bin:/usr/local/opt/pango/bin:/usr/local/opt/graphviz/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: pothosware/pothos/pothosflow 0.6.2 did not build
Logs:
     /Users/some.user/Library/Logs/Homebrew/pothosflow/00.options.out
     /Users/some.user/Library/Logs/Homebrew/pothosflow/01.cmake.cc
     /Users/some.user/Library/Logs/Homebrew/pothosflow/01.cmake
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/pothosware/homebrew-pothos/issues

These open issues may also help:
PothosFlow:  dyld: lazy symbol binding failed: Symbol not found:  https://github.com/pothosware/homebrew-pothos/issues/35
```

**Comment by guruofquality** [comment] 2020-05-04 14:49
This could be a work around, there are no C sources in the project, so im not sure what the cause is. Could be a cmake update and some check is more strict.

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 26fb932..a34ac3c 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -2,7 +2,7 @@
 # Project setup
 ########################################################################
 cmake_minimum_required(VERSION 2.8.9)
-project(PothosFlow CXX)
+project(PothosFlow CXX C)
 
 if(${CMAKE_PROJECT_NAME} STREQUAL ${PROJECT_NAME})
     find_package(Pothos "0.6.0" CONFIG REQUIRED)
```

**Comment by guruofquality** [comment] 2020-05-04 18:05
build all of the GUI toolkits with --head, the newer QT5 is somehow requiring C lang to be enabled. I dont know why

**Closed by guruofquality** 2020-05-04 18:05 UTC

**Comment by drfruct** [comment] 2020-05-07 18:37
I tried to compile other pothos projects, all except `pothoscomms` gave the same error.

The `pothoscomms` CMakeLists.txt contains `project(PothosComms CXX C)`.
Not all of them depend on `QT5`, but almost all depend on `poco`

Work around is the same, add `C` to `project`.

**Comment by guruofquality** [comment] 2020-05-07 19:08
Its poco, the cmake config file uses something from C and doesnt enable the language. I will add something common to PothosCore for this

**Comment by drfruct** [comment] 2020-05-08 06:37
After your last commit to `PothosCore` still no luck to compile `pothosblocks` and other pothos tools.
My actions:
```
brew uninstall pothos pothoscomms pothosflow
brew install --HEAD pothos
brew install --HEAD pothosblocks
```

On `pothosblocks` installation  I've got the same error about C language.

**Comment by guruofquality** [comment] 2020-05-08 14:47
Its the gift that keeps giving
https://github.com/pothosware/PothosCore/commit/8f929915a89ba071a8cc96fc05e71e105be1c30d

**Comment by drfruct** [comment] 2020-05-08 15:17
Everything compiles perfectly! Thank You!
