### ISSUE TITLE
Build issue using brew

### ISSUE THREAD

**Issue by supertorqued** [pothosware/homebrew-pothos#60] opened 2022-11-28 18:09 UTC
Following the instructions listed here: https://github.com/pothosware/homebrew-pothos/wiki...
I get the build error below on the brew install pothosaudio step.
...
1 error generated.
make[2]: *** [lib/CMakeFiles/Pothos.dir/System/Logger.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [lib/CMakeFiles/Pothos.dir/all] Error 2
make: *** [all] Error 2

Last 15 lines from /Users/tflug/Library/Logs/Homebrew/pothos/02.make:
        ^
/opt/homebrew/include/Poco/Net/DatagramSocket.h:51:2: note: candidate constructor not viable: requires at least 2 arguments, but 1 was provided
        DatagramSocket(const SocketAddress& address, bool reuseAddress, bool reusePort = false, bool ipV6Only = false);

**Comment by ncorgan** [comment] 2022-11-28 18:10
Duplicate of https://github.com/pothosware/homebrew-pothos/issues/59, solution already in progress

**Closed as not planned by ncorgan** 2022-11-28 18:10 UTC

**Comment by supertorqued** [comment] 2022-11-28 18:11
Thanks, I didn't find #59 in my searches. :)
